Support Angular 10
With Angular 10, the `ModuleWithProviders` interfaces has a mandatory generic parameter.

It is not given in ngx-date-fns : https://github.com/joanllenas/ngx-date-fns/blob/d009bb69811bc96201708c0ace6c794ae7e4f2f7/projects/ngx-date-fns/src/lib/date-fns.module.ts#L247

This results in the following error :

```
node_modules/ngx-date-fns/lib/date-fns.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

3     static forRoot(): ModuleWithProviders;
                        ~~~~~~~~~~~~~~~~~~~
```

This is a PR just to fix this, (it is unlikely but) there may be more changes needed elewhere.